### ISSUE TITLE
It is not playing video on Windows app and also on desktop

### ISSUE THREAD

**Issue by salim-hbk** [HiroyukTamura/double_tap_player_view#5]
It is not playing video on Windows app and also on desktop

**Comment by HiroyukTamura** [comment]
This package provides only a handler widget for double-tap / swipe gesture, so your issue is out of scope.
you mean the example doesn't work on the platform?
this is because the [video_player](https://pub.dev/packages/video_player) Plugin is only for web, android, and ios.
